model: ECAPA_TDNN
C: 1024
n_out: 192
batch_size: 16
n_per_speaker: 2
loss_function: angleproto
augment: True
max_epoch: 2
save_path: output/ECAPA_TDNN_AP
train_list: /kaggle/input/vin-project/data/data/metadata/train/training_metadata.txt
train_path: ./
test_list: /kaggle/input/vin-project/data/data/metadata/test/sample_test_pairs_with_label.txt
test_path: /kaggle/input/vin-project/data/data/test/sv_vlsp_2021/public_test/competition_public_test
musan_path: /kaggle/input/vin-project/data/data/musan_augment
rir_path: /kaggle/input/vin-project/data/data/rirs_noises
output_path: output/testing_results/public_test

