model: RawNet3
encoder_type: ASP
n_out: 512
sinc_stride: 10
batch_size: 16
n_per_speaker: 2
loss_function: angleproto
augment: True
max_epoch: 50
save_path: output/RawNet3_AP
train_list: data/metadata/train/training_metadata.txt
train_path: ./
test_list: data/metadata/test/sample_test_pairs.txt
test_path: data/test/sv_vlsp_2021/public_test/competition_public_test
musan_path: data/musan_augment
rir_path: data/rirs_noises
output_path: output/testing_results/public_test