model: SEResNet34
log_input: True
encoder_type: ASP
loss_function: aamsoftmax
n_classes: 1015
batch_size: 64
max_seg_per_spk: 1000
augment: True
max_epoch: 50
save_path: output/SEResNet34_ASP_AAM
train_list: /kaggle/input/vin-project/data/data/metadata/train/training_metadata.txt
train_path: /kaggle/input/vin-project/data/
test_list: /kaggle/input/vin-project/data/data/metadata/test/labels/public_test_pairs_with_label.txt
test_path: /kaggle/input/vin-project/data/data/test/sv_vlsp_2021/public_test/competition_public_test
musan_path: /kaggle/input/vin-project/data/data/musan_augment
rir_path: /kaggle/input/vin-project/data/data/rirs_noises
output_path: output/testing_results/public_test